name: Docker Builds

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches:
      - 'unstable'
      - 'v*.*.*'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'unstable'
      - 'v*.*.*'

permissions:
  contents: read
  packages: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-codeperf-pubsub-bench:
    runs-on: ubuntu-latest
    steps:
      # Get the repositery's code
      - name: Checkout
        uses: actions/checkout@v2

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Docker meta
        id: meta_codeperf
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            codeperf/redis-benchmark-go
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_codeperf.outputs.tags }}
          labels: ${{ steps.meta_codeperf.outputs.labels }}
